services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    hostname: homeassistant
    restart: unless-stopped
    privileged: true
    depends_on:
      - mosquitto
    networks:
      - proxy
      - homeassistant-net
    ports:
      - 8123:8123
    volumes:
      - ./config:/config
    environment:
      - TZ
    labels:
      - "traefik.http.routers.homeassistant.rule=Host(`home.${DOMAIN_NAME}`)"
      - "traefik.http.routers.homeassistant-external.rule=Host(`homeassistant.${DOMAIN_NAME}`)"
      - "traefik.docker.network=proxy" # Without specifying this a network is chosen randomly, so connecting via traefik only works 50% of the time
      - "traefik.http.routers.homeassistant.entrypoints=https"
      - "traefik.http.routers.homeassistant-external.entrypoints=https_external"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant-external.tls=true"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    hostname: mosquitto
    restart: unless-stopped
    networks:
      - homeassistant-net
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    environment:
      - TZ
    labels:
      - "traefik.enable=false"

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    hostname: frigate
    restart: unless-stopped
    privileged: true
    networks:
      - proxy
      - homeassistant-net
    ports:
      - 5000:5000
      - 1935:1935
    volumes:
      - ./frigate/config.yml:/config/config.yml:ro
      - ./frigate/db:/db
      - /mnt/nvr:/media/frigate
      - /dev/apex_0:/dev/apex_0 # Google Coral TPU
      - type: tmpfs # 1GB of memory, reduces SSD wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - TZ
    env_file:
      - frigate.env
    shm_size: "128mb"
    labels:
      - "traefik.http.routers.frigate.rule=Host(`frigate.${DOMAIN_NAME}`)"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frigate.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/run/secrets/traefik_login"
      - "traefik.http.routers.frigate.entrypoints=https"
      - "traefik.http.routers.frigate.tls=true"
      - "traefik.http.services.frigate.loadbalancer.server.port=5000"

networks:
  proxy:
    external: true
  homeassistant-net:
    name: homeassistant-net
